FoodRegistrationTool/Models/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FoodRegistrationTool.Models
{
    public class Product
    {
        public int ProductId { get; set; }

        [RegularExpression(@"[0-9a-zA-ZæøåÆØÅ. \-]{2,20}", ErrorMessage = "The name must be numbers or letters and between 2 to 20 chars.")]
        [Display(Name = "Product name")]
        public string Name { get; set; } = string.Empty;
        public string Category { get; set; } = string.Empty;
        public string Nutrition { get; set; } = string.Empty;

        [Range(0.01, double.MaxValue, ErrorMessage = "The price must be > 0.")]
        public decimal Price { get; set; }

        [StringLength(200)]
        public string? Description { get; set; }
        [Display(Name = "Image")]
        public string? ImageUrl { get; set; }
        public string? NutriScore { get; set; }

        // Doesn't put class in DB, handles image upload by using IFormFile which accepts image-files
        [NotMapped]
        [Display(Name = "Upload Image")]
        public IFormFile? ImageFile { get; set; }

        //Foreign Key
        public int ProducerId { get; set; }

        // Navigation property
        public virtual Producer Producer { get; set; } = default!;

        // Hvis det legges til nye klasser, kjør følgende i terminal (se async modulen i canvas):
        // dotnet ef migrations add FoodRegistryDbExpanded
        // dotnet ef database update 
    }
}

FoodRegistrationTool/ViewModels/ProductsViewModel.cs
using FoodRegistrationTool.Models;

namespace FoodRegistrationTool.ViewModels
{
    public class ProductsViewModel
    {
        public IEnumerable<Product> Products;
        public string? CurrentViewName;

        public ProductsViewModel(IEnumerable<Product> products, string? currentViewName)
        {
            Products = products;
            CurrentViewName = currentViewName;
        }
    }
}

FoodRegistrationTool/Controllers/ProducerController.cs
using Microsoft.AspNetCore.Mvc;
using FoodRegistrationTool.Models;
using FoodRegistrationTool.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace FoodRegistrationTool.Controllers;

public class ProducerController : Controller
{
    private readonly IProductRepository _productRepository;
    private readonly ILogger<ProducerController> _logger;

    public ProducerController(IProductRepository productRepository, ILogger<ProducerController> logger)
    {
        _productRepository = productRepository;
        _logger = logger;
    }

    // Table view
    public async Task<IActionResult> Table()
    {
        var producers = await _productRepository.GetAllProducers();
        if (producers == null)
        {
            _logger.LogError("[ProducerController] Producer list not found while executing _productRepository.GetAllProducers()");
            return NotFound("Producer list not found");
        }
        return View(producers);
    }

    // Create Producer
    [HttpGet]
    [Authorize]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [Authorize]
    public async Task<IActionResult> Create(Producer producer)
    {
        if (ModelState.IsValid)
        {
            // Save producer in DB
            bool returnOK = await _productRepository.CreateProducer(producer);
            if (returnOK)
            {
                return RedirectToAction(nameof(Table));
            }
        }
        _logger.LogError("[ProducerController] Producer creation failed {@producer}", producer);
        return View(producer);
    }

    // Update Producer
    [HttpGet]
    [Authorize]
    public async Task<IActionResult> Update(int id)
    {
        var producer = await _productRepository.GetProducerById(id);
        if (producer == null)
        {
            _logger.LogError("[ProducerController] Producer not found when updating ProducerId {ProducerId:0000}", id);
            return BadRequest("Producer not found for the ProducerId");
        }
        return View(producer);
    }

    [HttpPost]
    [Authorize]
    public async Task<IActionResult> Update(Producer producer)
    {
        if (ModelState.IsValid)
        {
            bool returnOK = await _productRepository.UpdateProducer(producer);
            if (returnOK)
            {
                return RedirectToAction(nameof(Table));
            }
        }
        _logger.LogError("[ProducerController] Producer update failed {@producer}", producer);
        return View(producer);
    }

    // Delete Producer
    [HttpGet]
    [Authorize]
    public async Task<IActionResult> Delete(int id)
    {
        var producer = await _productRepository.GetProducerById(id);
        if (producer == null)
        {
            _logger.LogError("[ProducerController] Producer not found for the PoducerId {ProducerId:0000}", id);
            return BadRequest("Producer not found for the ProducerId");
        }
        return View(producer);
    }

    [HttpPost]
    [Authorize]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        bool returnOK = await _productRepository.DeleteProducer(id);
        if (!returnOK)
        {
            _logger.LogError("[ProducerController] Producer deletion failed for the ProducerId {ProducerId}", id);
            return BadRequest("Producer deletion failed");
        }
        return RedirectToAction(nameof(Table));
    }
}

FoodRegistrationTool/Controllers/ProductController.cs
using FoodRegistrationTool.Models;
using Microsoft.AspNetCore.Mvc;
using FoodRegistrationTool.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using FoodRegistrationTool.DAL;
using System.Drawing.Printing;

namespace FoodRegistrationTool.Controllers;

public class ProductController : Controller
{
    private readonly IProductRepository _productRepository;
    private readonly ILogger<ProductController> _logger;

    // For image upload and viewing
    private readonly IWebHostEnvironment _hostEnvironment;

    public ProductController(IProductRepository productRepository, IWebHostEnvironment hostEnvironment, ILogger<ProductController> logger)
    {
        _productRepository = productRepository;
        _hostEnvironment = hostEnvironment;
        _logger = logger;
    }

    public async Task<IActionResult> Table()
    {
        var products = await _productRepository.GetAll();
        if (products == null)
        {
            _logger.LogError("[ProductController] Product list not found while executing _productRepository.GetAll()");
            return NotFound("Product list not found");
        }
        var productsViewModel = new ProductsViewModel(products, "Table");
        return View(productsViewModel);
    }

    public async Task<IActionResult> Grid()
    {
        var products = await _productRepository.GetAll();
        if (products == null)
        {
            _logger.LogError("[ProductController] Product list not found while executing _productRepository.GetAll()");
            return NotFound("Product list not found");
        }
        var productsViewModel = new ProductsViewModel(products, "Grid");
        return View(productsViewModel);
    }

    public async Task<IActionResult> Details(int id)
    {
        var product = await _productRepository.GetProductById(id);
        if (product == null)
        {
            _logger.LogError("[ProductController] Product not found for the ProductId {ProductId:0000}", id);
            return NotFound("Product not found for the ProductId");
        }
        return View(product);
    }

    [HttpGet]
    [Authorize]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [Authorize]
    public async Task<IActionResult> Create([Bind("ProductId,Name,Category,Nutrition,NutriScore,Price,Description, ProducerId")] ProductCreateViewModel productCreateViewModel)
    {
        // Må legge inn Logger her
        if (ModelState.IsValid)
        {
            // Getting producer by Id
            var producer = await _productRepository.GetProducerById(productCreateViewModel.ProducerId);

            // Checking producer exists
            if (producer == null)
            {
                _logger.LogError("[ProductController] Producer not found for the ProducerId {ProducerId:0000}", productCreateViewModel.ProducerId);
                return BadRequest("Producer not found.");
            }

            // Creating Product object
            var product = new Product
            {
                Name = productCreateViewModel.Name,
                Category = productCreateViewModel.Category,
                Nutrition = productCreateViewModel.Nutrition,
                Price = productCreateViewModel.Price,
                Description = productCreateViewModel.Description,
                NutriScore = productCreateViewModel.NutriScore,
                ProducerId = productCreateViewModel.ProducerId,
                Producer = producer // Sett produsenten til produktet
            };

            // Handle Image Upload
            /* 
               FirstOrDefault() is a method that returns the first element of the source,
               which in this case can only be the variable 'IFormFile ImageFile' from the model Product, or a null reference. 
               IFormFile accepts file-formats as parameters, such that an image-file can be submitted.
            */
            var imageFile = Request.Form.Files.FirstOrDefault();
            if (imageFile != null)
            {
                // Sets absolute path to wwwroot with the property WebRootPath
                string wwwRootPath = _hostEnvironment.WebRootPath;
                // Seperates filename and extension (filename.jpeg or filename.png, etc..)
                string fileName = Path.GetFileNameWithoutExtension(imageFile.FileName);
                string extension = Path.GetExtension(imageFile.FileName);
                // Sets time and date of when the image-file is created, and attaches it to the name of the client-file in wwwroot
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                // Get path of where the file will be stored
                string path = Path.Combine(wwwRootPath, "images/clientImages", fileName);
                //Console.WriteLine($"Attempting to save file to: {path}");
                // Creates an object fileStream from the class FileStream which can read and write to the file
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    // Copies contents of imageFile into the object fileStream with async.
                    await imageFile.CopyToAsync(fileStream);
                }
                // Get URL of the created image so that it is stored in the DB, and not the ImageFile itself.
                product.ImageUrl = "/images/clientImages/" + fileName;
                //Console.Write($"Set url to: {product.ImageUrl}");

            }
            else
            {
                _logger.LogError("[ProductController] ImageUrl not found for the ImageFile {product.ImageUrl}", product.ImageUrl);
                Console.Write($"No img found, url: {product.ImageUrl}, imgfile: {product.ImageFile}");
            }

            // Save product to DB
            await _productRepository.Create(product);
            return RedirectToAction(nameof(Table));
        }
        return View(productCreateViewModel);
    }

    [HttpGet]
    [Authorize]
    public async Task<IActionResult> Update(int id)
    {
        var product = await _productRepository.GetProductById(id);
        if (product == null)
        {
            _logger.LogError("[ProductController] Product not found when updating the ProductId {ProductId:0000}", id);
            return BadRequest("Product not found for the ProductId");
        }
        // Map Product to ProductUpdateViewModel
       var productUpdateViewModel = new ProductUpdateViewModel
       {
           ProductId = product.ProductId,
           Name = product.Name,
           Category = product.Category,
           Nutrition = product.Nutrition,
           Price = product.Price,
           Description = product.Description,
           ProducerId = product.ProducerId,
           // Map other properties as needed
       };
        return View(productUpdateViewModel);
    }

    [HttpPost]
    [Authorize]
    public async Task<IActionResult> Update(int id, [Bind("ProductId,Name,Category,Nutrition,NutriScore,Price,Description,ProducerId")] ProductUpdateViewModel productUpdateViewModel) //Product product)
    {
        
        if (ModelState.IsValid)
        {
            try
            {
                _logger.LogInformation("[ProductController] Product can be updated");
                // Retrieve the existing product from the repository
                var product = await _productRepository.GetProductById(id);
                if (product == null)
                {
                    _logger.LogError("[ProductController] Product not found for the ProductId {ProductId:0000}", id);
                    return NotFound();
                }
                if (id != product.ProductId)
                {
                    _logger.LogError("[ProductController] ProductId not found");
                    return NotFound();
                }

                // Update the product properties
                product.ProductId = productUpdateViewModel.ProductId;
                product.Name = productUpdateViewModel.Name;
                product.Category = productUpdateViewModel.Category;
                product.Nutrition = productUpdateViewModel.Nutrition;
                product.NutriScore = productUpdateViewModel.NutriScore;
                product.Price = productUpdateViewModel.Price;
                product.Description = productUpdateViewModel.Description;
                product.ProducerId = productUpdateViewModel.ProducerId;

                // Handle Image Upload
                var imageFile = Request.Form.Files.FirstOrDefault();
                if (imageFile != null)
                {
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(imageFile.FileName);
                    string extension = Path.GetExtension(imageFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    string path = Path.Combine(wwwRootPath + "/images/clientImages", fileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(fileStream);
                    }
                    product.ImageUrl = "/images/clientImages/" + fileName;

                    // Delete old image
                    var oldImagePath = Path.Combine(wwwRootPath, "images/clientImages", product.ImageUrl);//product.ImageUrl);
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                _logger.LogInformation("[ProductController] Product can be updated for product {product.ProductId}", product.ProductId);

FoodRegistrationTool/Views/Shared/_Carousel.cshtml
<div id="carouselHome" class="carousel slide" data-bs-ride="carousel">
    <ol class="carousel-indicators">
        <li data-bs-target="#carouselHome" data-bs-slide-to="0" class="active"></li>
        <li data-bs-target="#carouselHome" data-bs-slide-to="1"></li>
        <li data-bs-target="#carouselHome" data-bs-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/images/carousel3.jpg" alt="First slide">
            <div class="carousel-caption d-none d-md-block caption-bg">
                <h5>Baked Chicken Leg</h5>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque nisi sapiente quas minima, deleniti
                    blanditiis minus dolorum expedita nam excepturi quasi ipsa nihil eius autem? Fugit laborum soluta
                    blanditiis sapiente.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/carousel2.jpg" alt="Second slide">
            <div class="carousel-caption d-none d-md-block caption-bg">
                <h5>Barbeque</h5>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque nisi sapiente quas minima, deleniti
                    blanditiis minus dolorum expedita nam excepturi quasi ipsa nihil eius autem? Fugit laborum soluta
                    blanditiis sapiente.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/carousel1.jpg" alt="Third slide">
            <div class="carousel-caption d-none d-md-block caption-bg">
                <h5>Grilled Veggies</h5>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque nisi sapiente quas minima, deleniti
                    blanditiis minus dolorum expedita nam excepturi quasi ipsa nihil eius autem? Fugit laborum soluta
                    blanditiis sapiente.</p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselHome" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselHome" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </a>
</div>

<style>
    /* Adds a dark transparent background to the caption */
    .caption-bg {
        background-color: rgba(0, 0, 0, 0.5);
        /* Adjust opacity as needed */
        padding: 15px;
        /* Optional padding */
        border-radius: 8px;
        /* Optional rounded corners */
    }
</style>

FoodRegistrationTool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoodRegistrationTool</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/FoodRegistrationTool.styles.css" asp-append-version="true" />
    <script src="~/js/bootstrap.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/table-nutrition.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/js/jquery.validate.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.js"></script>

</head>

<body class="m-0">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand">Food Registry</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producer"
                                asp-action="Table">Producers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product"
                                asp-action="Table">Products</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="main-container container-fluid p-0 mb-0">
        <main role="main">
            @RenderBody()

        </main>
    </div>

    <footer class="text-center footer-custom">
        <div class="container justify-content-center p-4">
            <div class="row">
                <div class="col-sm-4 mb-4 mb-md-0">
                    <p class="text-uppercase"><strong>Food Registry</strong></p>
                </div>

                <div class="col-sm-4 mb-4 mb-md-0">
                    <p class="text-uppercase"><strong>Contact</strong></p>
                    <p>Phone: +123 456 7890</p>
                    <p>Email: info@foodregistry.com</p>
                </div>

                <div class="col-sm-4 mb-4 mb-md-0">
                    <p class="text-uppercase"><strong>Address</strong></p>
                    <p>1234 Food Street</p>
                    <p>Oslo, Norway</p>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

FoodRegistrationTool/Views/Shared/_ProducerProductTable.cshtml
@model IEnumerable<Product>

<table class="table table-striped table-hover custom-table" style="max-width: 1200px;">
    <caption><strong>Products</strong></caption>
    <thead>
        <tr class="table-header">
            <th>Image</th>
            <th>Product</th>
            <th>Category</th>
            <th>NutriScore</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
            <tr>
                <td>
                    <img src="@product.ImageUrl" class="product-thumbnail" alt="@product.Name" />
                </td>
                <td>
                    <a asp-area="" asp-controller="Product" asp-action="Details"
                        asp-route-id="@product.ProductId">@product.Name</a>
                </td>
                <td>
                    @product.Category
                </td>
                <td>
                    <span class="nutrition-score" data-score="@product.NutriScore">@product.NutriScore</span>
                </td>
            </tr>
        }
    </tbody>
</table>

FoodRegistrationTool/Views/Shared/_ProductCard.cshtml
@model Product

<div class="col mb-4">
    <div class="card h-100 shadow-sm border">
        <img src="@Model.ImageUrl" class="card-img-top p-4 fixed-height-img-card" alt="@Model.Name" />
        <div class="card-body">
            <div class="card-title">
                <h2 class="h5 text-start">
                    <a asp-asp-controller="Product" asp-action="Details" asp-route-id="@Model.ProductId">@Model.Name</a>
                </h2>
                <p class="card-text">
                    <span class="nutrition-score" data-score="@Model.NutriScore">@Model.NutriScore</span>
                </p>
                <p class="card-text">
                    @Model.Nutrition
                </p>
                <p class="card-text">
                    @Model.Price.ToString("0.00 NOK")
                </p>
            </div>
        </div>
    </div>
</div>

FoodRegistrationTool/Views/Shared/_ProductTable.cshtml
@model IEnumerable<Product>

<div class="table-responsive">
    <table class="table table-hover custom-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Category</th>
                <th>Nutrition</th>
                <th><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC9421047/" target="_blank"
                        title="Nutri-Score Article">Score</a></th>
                <th>Price</th>
                <th>Description</th>
                <th>Image</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model)
            {
                <tr>
                    <td>@product.ProductId</td>
                    <td>
                        <a asp-controller="Product" asp-action="Details" asp-route-id="@product.ProductId">@product.Name</a>
                    </td>
                    <td>@product.Category</td>
                    <td>@product.Nutrition</td>
                    <td>
                        <span class="nutrition-score" data-score="@product.NutriScore">@product.NutriScore</span>
                    </td>
                    <td>@product.Price.ToString("0.00 NOK")</td>
                    <td class="description-cell">@product.Description</td>
                    <td>
                        @if (!string.IsNullOrEmpty(product.ImageUrl))
                        {
                            <img src="@product.ImageUrl" alt="@product.Name" class="product-thumbnail" />
                        }
                        else
                        {
                            <span>No image</span>
                        }
                    </td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Product Action Buttons">
                            <a asp-action="Update" asp-route-id="@product.ProductId"
                                class="btn btn-sm btn-outline-primary">Update</a>
                            <a asp-action="Delete" asp-route-id="@product.ProductId"
                                class="btn btn-sm btn-outline-danger">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>